---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: annotiation-mutating-acc
  labels:
    heritage: annotiation-mutating
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: annotiation-mutating
  labels:
    heritage: annotiation-mutating
rules:
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["create", "list", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: annotiation-mutating
  labels:
    heritage: annotiation-mutating
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: annotiation-mutating
subjects:
  - kind: ServiceAccount
    name: annotiation-mutating-acc
    namespace: {{ .Release.Namespace }}