apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.shellOperator.webhookServiceName }}
  labels:
    heritage: annotiation-mutating
spec:
#  type: LoadBalancer
#  externalTrafficPolicy: Local
  ports:
    - name: webhook
      port: 443
      targetPort: 9680
      protocol: TCP
  selector:
    app: dynatrace-annotiation-mutating